# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # Restore dependencies for the test project
    - name: Restore dependencies
      run: dotnet restore POSCashRegister.Tests/PosCashRegister.Tests.csproj

    # Build the test project
    - name: Build
      run: dotnet build POSCashRegister.Tests/PosCashRegister.Tests.csproj --no-restore

    # Run tests for the test project
    - name: Test
      run: dotnet test POSCashRegister.Tests/PosCashRegister.Tests.csproj --no-build --verbosity normal
